require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/daily_menus", type: :request do

before { sign_in user, scope: :user }

  let!(:user) { create(:user) }
  let(:valid_attributes) { attributes_for(:daily_menu) }
  let(:invalid_attributes) { { date: nil } }

  before { sign_in user, scope: :user }

  describe "GET /index" do
    it "renders a successful response" do
      DailyMenu.create! valid_attributes
      get daily_menus_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      daily_menu = DailyMenu.create! valid_attributes
      get daily_menu_path(daily_menu)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_daily_menu_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      daily_menu = DailyMenu.create! valid_attributes
      get edit_daily_menu_path(daily_menu)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DailyMenu" do
        expect {
          post daily_menus_path, params: { daily_menu: valid_attributes }
        }.to change(DailyMenu, :count).by(1)
      end

      it "redirects to the created daily_menu" do
        post daily_menus_path, params: { daily_menu: valid_attributes }
        expect(response).to redirect_to(daily_menu_path(DailyMenu.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DailyMenu" do
        expect {
          post daily_menus_path, params: { daily_menu: invalid_attributes }
        }.to change(DailyMenu, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post daily_menus_path, params: { daily_menu: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested daily_menu" do
        daily_menu = DailyMenu.create! valid_attributes
        patch daily_menu_path(daily_menu), params: { daily_menu: valid_attributes.merge(date: Date.tomorrow) }
        daily_menu.reload
        expect(daily_menu.date).to eq(Date.tomorrow)
      end

      it "redirects to the daily_menu" do
        daily_menu = DailyMenu.create! valid_attributes
        patch daily_menu_path(daily_menu), params: { daily_menu: valid_attributes.merge(date: Date.tomorrow) }
        daily_menu.reload
        expect(response).to redirect_to(daily_menu_path(daily_menu))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        daily_menu = DailyMenu.create! valid_attributes
        patch daily_menu_path(daily_menu), params: { daily_menu: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested daily_menu" do
      daily_menu = DailyMenu.create! valid_attributes
      expect {
        delete daily_menu_path(daily_menu)
      }.to change(DailyMenu, :count).by(-1)
    end

    it "redirects to the daily_menus list" do
      daily_menu = DailyMenu.create! valid_attributes
      delete daily_menu_path(daily_menu)
      expect(response).to redirect_to(daily_menus_path)
    end
  end
end
