require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/daily_menu_items", type: :request do

before { sign_in user, scope: :user }

  let!(:user) { create(:user) }
  let!(:daily_menu) { create(:daily_menu) }
  let(:valid_attributes) { attributes_for(:daily_menu_item).merge(daily_menu_id: daily_menu.id) }
  let(:invalid_attributes) { { name: "", description: "", category: "", daily_menu_id: nil } }

  before { sign_in user, scope: :user }

  describe "GET /index" do
    it "renders a successful response" do
      DailyMenuItem.create! valid_attributes
      get daily_menu_items_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      daily_menu_item = DailyMenuItem.create! valid_attributes
      get daily_menu_item_path(daily_menu_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_daily_menu_item_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      daily_menu_item = DailyMenuItem.create! valid_attributes
      get edit_daily_menu_item_path(daily_menu_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DailyMenuItem" do
        expect {
          post daily_menu_items_path, params: { daily_menu_item: valid_attributes }
        }.to change(DailyMenuItem, :count).by(1)
      end

      it "redirects to the created daily_menu_item" do
        post daily_menu_items_path, params: { daily_menu_item: valid_attributes }
        expect(response).to redirect_to(daily_menu_item_path(DailyMenuItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DailyMenuItem" do
        expect {
          post daily_menu_items_path, params: { daily_menu_item: invalid_attributes }
        }.to change(DailyMenuItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post daily_menu_items_path, params: { daily_menu_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested daily_menu_item" do
        daily_menu_item = DailyMenuItem.create! valid_attributes
        patch daily_menu_item_path(daily_menu_item), params: { daily_menu_item: valid_attributes.merge(name: "Updated Soup") }
        daily_menu_item.reload
        expect(daily_menu_item.name).to eq("Updated Soup")
      end

      it "redirects to the daily_menu_item" do
        daily_menu_item = DailyMenuItem.create! valid_attributes
        patch daily_menu_item_path(daily_menu_item), params: { daily_menu_item: valid_attributes.merge(name: "Updated Soup") }
        daily_menu_item.reload
        expect(response).to redirect_to(daily_menu_item_path(daily_menu_item))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        daily_menu_item = DailyMenuItem.create! valid_attributes
        patch daily_menu_item_path(daily_menu_item), params: { daily_menu_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested daily_menu_item" do
      daily_menu_item = DailyMenuItem.create! valid_attributes
      expect {
        delete daily_menu_item_path(daily_menu_item)
      }.to change(DailyMenuItem, :count).by(-1)
    end

    it "redirects to the daily_menu_items list" do
      daily_menu_item = DailyMenuItem.create! valid_attributes
      delete daily_menu_item_path(daily_menu_item)
      expect(response).to redirect_to(daily_menu_items_path)
    end
  end
end
