require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/grocery_lists", type: :request do

  let!(:user) { create(:user) }
  before { sign_in user, scope: :user }
  let!(:daily_menu) { create(:daily_menu) }
  let(:valid_attributes) {
    { daily_menu_id: daily_menu.id }
  }

  let(:invalid_attributes) {
    { daily_menu_id: nil }
  }

  describe "GET /index" do
    it "renders a successful response" do
      create(:grocery_list, daily_menu: daily_menu)
      get grocery_lists_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      grocery_list = create(:grocery_list, daily_menu: daily_menu)
      get grocery_list_path(grocery_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_grocery_list_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      grocery_list = create(:grocery_list, daily_menu: daily_menu)
      get edit_grocery_list_path(grocery_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GroceryList" do
        expect {
          post grocery_lists_path, params: { grocery_list: valid_attributes }
        }.to change(GroceryList, :count).by(1)
      end

      it "redirects to the created grocery_list" do
        post grocery_lists_path, params: { grocery_list: valid_attributes }
        expect(response).to redirect_to(grocery_list_path(GroceryList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GroceryList" do
        expect {
          post grocery_lists_path, params: { grocery_list: invalid_attributes }
        }.to change(GroceryList, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post grocery_lists_path, params: { grocery_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { daily_menu_id: create(:daily_menu).id }
      }

      it "updates the requested grocery_list" do
        grocery_list = create(:grocery_list, daily_menu: daily_menu)
        patch grocery_list_url(grocery_list), params: { grocery_list: new_attributes }
        grocery_list.reload
        expect(grocery_list.daily_menu_id).to eq(new_attributes[:daily_menu_id])
      end

      it "redirects to the grocery_list" do
        grocery_list = create(:grocery_list, daily_menu: daily_menu)
        patch grocery_list_url(grocery_list), params: { grocery_list: new_attributes }
        grocery_list.reload
        expect(response).to redirect_to(grocery_list_url(grocery_list))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        grocery_list = create(:grocery_list, daily_menu: daily_menu)
        patch grocery_list_url(grocery_list), params: { grocery_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested grocery_list" do
      grocery_list = create(:grocery_list, daily_menu: daily_menu)
      expect {
        delete grocery_list_url(grocery_list)
      }.to change(GroceryList, :count).by(-1)
    end

    it "redirects to the grocery_lists list" do
      grocery_list = create(:grocery_list, daily_menu: daily_menu)
      delete grocery_list_url(grocery_list)
      expect(response).to redirect_to(grocery_lists_url)
    end
  end
end
