require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ingredients", type: :request do

before { sign_in user, scope: :user }

  let!(:user) { create(:user) }
  let!(:menu_item) { create(:menu_item) }
  let(:valid_attributes) { attributes_for(:ingredient).merge(menu_item_id: menu_item.id) }
  let(:invalid_attributes) { { name: "", quantity: "", menu_item_id: nil } }

  before { sign_in user, scope: :user }

  describe "GET /index" do
    it "renders a successful response" do
      Ingredient.create! valid_attributes
      get ingredients_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ingredient = Ingredient.create! valid_attributes
      get ingredient_path(ingredient)

    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ingredient_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ingredient = Ingredient.create! valid_attributes
      get edit_ingredient_path(ingredient)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ingredient" do
        expect {
          post ingredients_path, params: { ingredient: valid_attributes }
        }.to change(Ingredient, :count).by(1)
      end

      it "redirects to the created ingredient" do
        post ingredients_path, params: { ingredient: valid_attributes }
        expect(response).to redirect_to(ingredient_path(Ingredient.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ingredient" do
        expect {
          post ingredients_path, params: { ingredient: invalid_attributes }
        }.to change(Ingredient, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post ingredients_path, params: { ingredient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ingredient" do
        ingredient = Ingredient.create! valid_attributes
        patch ingredient_path(ingredient), params: { ingredient: valid_attributes.merge(name: "Pepper") }
        ingredient.reload
        expect(ingredient.name).to eq("Pepper")
      end

      it "redirects to the ingredient" do
        ingredient = Ingredient.create! valid_attributes
        patch ingredient_path(ingredient), params: { ingredient: valid_attributes.merge(name: "Pepper") }
        ingredient.reload
        expect(response).to redirect_to(ingredient_path(ingredient))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ingredient = Ingredient.create! valid_attributes
        patch ingredient_path(ingredient), params: { ingredient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ingredient" do
      ingredient = Ingredient.create! valid_attributes
      expect {
        delete ingredient_path(ingredient)
      }.to change(Ingredient, :count).by(-1)
    end

    it "redirects to the ingredients list" do
      ingredient = Ingredient.create! valid_attributes
      delete ingredient_path(ingredient)
      expect(response).to redirect_to(ingredients_path)
    end
  end
end
