require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/menu_items", type: :request do

before { sign_in user, scope: :user }

  let!(:user) { create(:user) }
  let(:valid_attributes) { attributes_for(:menu_item) }
  let(:invalid_attributes) { { name: "", description: "", category: "" } }

  before { sign_in user, scope: :user }

  describe "GET /index" do
    it "renders a successful response" do
      MenuItem.create! valid_attributes
      get menu_items_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      menu_item = MenuItem.create! valid_attributes
      get menu_item_path(menu_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_menu_item_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      menu_item = MenuItem.create! valid_attributes
      get edit_menu_item_path(menu_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MenuItem" do
        expect {
          post menu_items_path, params: { menu_item: valid_attributes }
        }.to change(MenuItem, :count).by(1)
      end

      it "redirects to the created menu_item" do
        post menu_items_path, params: { menu_item: valid_attributes }
        expect(response).to redirect_to(menu_item_path(MenuItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MenuItem" do
        expect {
          post menu_items_path, params: { menu_item: invalid_attributes }
        }.to change(MenuItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post menu_items_path, params: { menu_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested menu_item" do
        menu_item = MenuItem.create! valid_attributes
        patch menu_item_path(menu_item), params: { menu_item: valid_attributes.merge(name: "Updated Dish") }
        menu_item.reload
        expect(menu_item.name).to eq("Updated Dish")
      end

      it "redirects to the menu_item" do
        menu_item = MenuItem.create! valid_attributes
        patch menu_item_path(menu_item), params: { menu_item: valid_attributes.merge(name: "Updated Dish") }
        menu_item.reload
        expect(response).to redirect_to(menu_item_path(menu_item))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        menu_item = MenuItem.create! valid_attributes
        patch menu_item_path(menu_item), params: { menu_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested menu_item" do
      menu_item = MenuItem.create! valid_attributes
      expect {
        delete menu_item_path(menu_item)
      }.to change(MenuItem, :count).by(-1)
    end

    it "redirects to the menu_items list" do
      menu_item = MenuItem.create! valid_attributes
      delete menu_item_path(menu_item)
      expect(response).to redirect_to(menu_items_path)
    end
  end
end
